name: Printing the output 
on: 
  workflow_dispatch:
      inputs:
        name:
        description: 'Person to greet '
        default: 'kanishka'
        type: string
          
      required: true

      jobs:   
        Send greeting:
          runs-on: ubuntu-latest
          steps:
           - name: Send greeting
             run: echo "Hello ${{ inputs.name}}"

            

