name: Greet User 
on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet '
        default: 'kanishka'
        type: string
        required: true

jobs:
  send_greeting:
    runs-on: ubuntu-latest
    steps:
      - name: send greeting
        run: echo "Hello ${{ inputs.name}}"

            

